
apiVersion: v1
kind: Pod
metadata:
  name: yolo-v3
  labels:
    name: yolo
spec:
  containers:
  - name: yolo-container
    image: python:3.10
    args: 
    - "/bin/bash"
    - "-c"
    - "git clone https://github.com/slahmer97/ICT4IALAB.git ict4ia && cd ict4ia/api && chmod +x ./run.sh && ./run.sh && sleep infinity"
    ports:
    - containerPort: 8000
              
    
    
